name: 'Publish EDD SL Release'
description: 'Publishes a new EDD SL release.'
inputs:
  composer-install:
    description: 'Whether to install composer dependencies.'
    required: false
    default: 'true'
  config-file:
    description: 'Relative path to your configuration file.'
    required: false
    default: 'edd-sl-release.json'
runs:
  using: 'composite'
  steps:
    # Create zip file and attach to release.
    - name: Create release zip
      id: create-zip
      uses: ashleyfae/action-build-release-zip@main
      with:
        composer-install: ${{ inputs.composer-install }}

    # Parse the release config.
    - name: Upload release
      env:
        RELEASE_CONFIG: ${{ inputs.config-file }}
        PRE_RELEASE: ${{ github.event.release.pre_release }}
        RELEASE_ZIP: ${{ steps.create-zip.outputs.zip-path }}
        RELEASE_FILE_NAME: ${{ steps.create-zip.outputs.file-name }}
      shell: bash
      run: ${{ github.action_path }}/release.sh
