name: 'Publish EDD SL Release'
description: 'Publishes a new EDD SL release.'
inputs:
  asset-url:
    description: 'URL to the release zip file.'
    required: true
  file-name:
    description: 'Name of the release zip file.'
    required: true
  pre-release:
    description: 'Whether this is a pre-release.'
    required: false
    default: 'false'
  readme-file:
    description: 'Relative path to your readme.txt file.'
    required: false
    default: 'readme.txt'
runs:
  using: 'composite'
  steps:
    - name: Publish release to EDD SL
      env:
        ASSET_URL: ${{ inputs.asset-url }}
        FILE_NAME: ${{ inputs.file-name }}
        README_FILE: ${{ inputs.readme-file }}
        RELEASE_VERSION: ${{ github.event.release.tag_name }}
        PRE_RELEASE: ${{ inputs.pre-release }}
        WORDPRESS_USER: ${{ env.WORDPRESS_USER }}
        WORDPRESS_PASS: ${{ env.WORDPRESS_PASS }}
        WORDPRESS_RELEASE_URL: ${{ env.WORDPRESS_RELEASE_URL }}
      shell: bash
      run: node ${{ github.action_path }}/publish-release.js
